version: '3'
services:

  cardano-sl:
    container_name: cardano-sl
    build: ./cardano-sl
    network_mode: "host"
    ports:
      - "8090:8090"
    volumes:
      - cardano-sl-db:/cardano-sl/state-wallet-mainnet/db

  daedalus:
    container_name: daedalus
    depends_on:
      - cardano-sl
    build: ./daedalus
    network_mode: "host"
    environment:
      DISPLAY: "$DISPLAY"
      XAUTHORITY: "/tmp/.docker.xauth"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - ./tls:/home/daedalus/daedalus/tls/ca

volumes:
  cardano-sl-db: